Timeline styling
techswitch-learners/mars-mission-may pull request #22
Opened 2021-06-24 14:50 UTC by IsmatMahmood1

https://trello.com/c/lRK3slOS/34-create-the-styling-of-the-timeline-page

2021-06-24 21:24 UTC, oskarwilliams378 reviewed
Can I see a screenshot of what this looks like at a couple different widths, as it looks very odd to me
![desktop](https://user-images.githubusercontent.com/84725775/123392281-c7dda580-d594-11eb-8620-d584132d763b.jpg)
![mobile](https://user-images.githubusercontent.com/84725775/123392285-c90ed280-d594-11eb-8e7a-619997ad7a67.jpg)
![tablet](https://user-images.githubusercontent.com/84725775/123392329-d7f58500-d594-11eb-83e4-86385c2f2dfd.jpg)

2021-06-24 21:24 UTC, oskarwilliams378 commented on src/components/Timeline.tsx
> +
new line not needed :)

2021-06-24 21:24 UTC, oskarwilliams378 commented on src/styles/Timeline.scss
> +
blank new line :)

2021-06-24 21:24 UTC, oskarwilliams378 commented on src/styles/Timeline.scss
> +
Blank new line

2021-06-24 21:24 UTC, oskarwilliams378 commented on src/components/Timeline.tsx
> +import "../styles/timeline.scss";
this should be capital t for timeline

2021-06-24 21:25 UTC, oskarwilliams378 requested changes
Meant to make it a request changes sorry

2021-06-25 10:25 UTC, oskarwilliams378 requested changes

2021-06-25 10:25 UTC, oskarwilliams378 commented on src/components/Card.tsx
> +    body: string | null | undefined;
not sure this is needed

2021-06-25 10:27 UTC, IsmatMahmood1 commented
New screen 
![desktop2](https://user-images.githubusercontent.com/84725775/123411392-51e33980-d5a8-11eb-9fb3-1347eaa51f66.jpg)
![mobile2](https://user-images.githubusercontent.com/84725775/123411401-527bd000-d5a8-11eb-96b6-ca8da3a02ba1.jpg)
![mobile2Smaller](https://user-images.githubusercontent.com/84725775/123411403-53146680-d5a8-11eb-81f6-6fc9d16a601b.jpg)
![tablet2](https://user-images.githubusercontent.com/84725775/123411405-53146680-d5a8-11eb-972e-1f67ccc23cb7.jpg)
shoots

2021-06-25 11:06 UTC, oskarwilliams378 approved these changes

2021-06-25 11:09 UTC, merged